// Code generated by OpenAI ChatGPT on Jul 30th, 2025 at 21:06 CST

import xml2js from "xml2js";

export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  const { tracking_number } = req.body;
  if (!tracking_number) {
    return res.status(400).json({ error: "tracking_number is required" });
  }

  const USER_ID = process.env.USPS_USER_ID;
  if (!USER_ID) {
    return res.status(500).json({ error: "USPS_USER_ID not configured" });
  }

  // Construct USPS API URL with XML query
  const xmlRequest = `<TrackRequest USERID="${USER_ID}"><TrackID ID="${tracking_number}"></TrackID></TrackRequest>`;
  const encodedXML = encodeURIComponent(xmlRequest);
  const url = `https://secure.shippingapis.com/ShippingAPI.dll?API=TrackV2&XML=${encodedXML}`;

  try {
    const response = await fetch(url);
    const xml = await response.text();

    // Parse XML to JSON
    xml2js.parseString(xml, { explicitArray: false }, (err, result) => {
      if (err) {
        return res.status(500).json({ error: "Failed to parse USPS XML response" });
      }
      res.status(200).json(result);
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
}
